In [ ]:
#Agenda
#implementation of Linear,Logistic,Decision Tree, Random Forest

# Linear Regression Part

In [ ]:
#1. Load the dataset using pandas
# 2. Extract data fromYearsExperience column is a variable named X
# 3. Extract data from salary column is a variable named Y
# 4. Divide the dataset into two parts for training and testing in 66% and 33% proportion
# 5. Create and train LinearRegression Model on training set
# 6. Make predictions based on the testing set using the trained model
# 7. Check the performance by calculating the r2 score of the model

In [ ]:
#1. Load the dataset using pandas
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('data.csv')
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
#2. Extract data fromYearsExperience column is a variable named X
X = dataset.iloc[:,:-1]

In [ ]:
#3. Extract data from salary column is a variable named Y
Y = dataset.iloc[:,-1]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 66% and 33% proportion
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1) 

In [ ]:
#5. Create and train LinearRegression Model on training set
from sklearn.linear_model import LinearRegression
lin = LinearRegression()
lin.fit(X_train,Y_train)

LinearRegression()

In [ ]:
#6. Make predictions based on the testing set using the trained model
lin_pred = lin.predict(X_test)
#7. Check the performance by calculating the r2 score of the model

# Logistic Regression Part

In [ ]:
# #1. Load the dataset using pandas
# 2. Extract data fromOutcome column is a variable named Y
# 3. Extract data from every column except Outcome column in a variable named X
# 4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
# 5. Create and train Logistic Regression Model on training set
# 6. Make predictions based on the testing set using the trained model
# 7. Check the performance by calculating the confusion matrix and accuracy score of the model 

In [ ]:
#1. Load the dataset using pandas
dd = pd.read_csv('diabetes.csv')
dd.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#2. Extract data fromOutcome column is a variable named Y
Y = dd.iloc[:,-1]

In [ ]:
#3. Extract data from every column except Outcome column in a variable named X
X = dd.iloc[:,:-1]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
#from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1)

In [ ]:
#5. Create and train Logistic Regression Model on training set
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
#6. Make predictions based on the testing set using the trained model
Y_pred = logmodel.predict(X_test)

In [ ]:
#7. Check the performance by calculating the confusion matrix and accuracy score of the model 
from sklearn.metrics import confusion_matrix,accuracy_score
result = confusion_matrix(Y_pred,Y_test)
result

array([[132,  36],
       [ 14,  49]], dtype=int64)

In [ ]:
acc = accuracy_score(Y_pred,Y_test)
acc

0.7835497835497836

In [ ]:
print(132 + 49)
print(132+ 36 + 14 + 49)
print(((132+49)/(132+ 36 + 14 + 49))*100)

181
231
78.35497835497836


# Decision Tree Part

In [ ]:
# 1. Load the dataset using pandas
# 2. Extract data fromOutcome column is a variable named Y
# 3. Extract data from every column except Outcome column in a variable named X
# 4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
# 5. Create and train Decision Tree Model on training set
# 6. Make predictions based on the testing set using the trained model
# 7. Check the performance by calculating the confusion matrix and accuracy score of the model 

In [ ]:
#1. Load the dataset using pandas
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#2. Extract data fromOutcome column is a variable named Y
Y = data.iloc[:,-1]

In [ ]:
#3. Extract data from every column except Outcome column in a variable named X
X = data.iloc[:,:-1]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
#from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1)

In [ ]:
#5. Create and train Decision Tree Model on training set
from sklearn.tree import DecisionTreeClassifier
cls = DecisionTreeClassifier()
cls.fit(X_train,Y_train)

DecisionTreeClassifier()

In [ ]:
#6. Make predictions based on the testing set using the trained model
Y_pred = cls.predict(X_test)

In [ ]:
#7. Check the performance by calculating the confusion matrix and accuracy score of the model
#from sklearn.metrics import confusion_matrix,accuracy_score
results = confusion_matrix(Y_pred,Y_test)
results

array([[116,  42],
       [ 30,  43]], dtype=int64)

In [ ]:
acc = accuracy_score(Y_pred,Y_test)
acc

0.6883116883116883

In [ ]:
print((116+43)/(116+42+30+43))

0.6883116883116883


# Random Forest Part

In [ ]:
# 1. Load the dataset using pandas
# 2. Extract data fromOutcome column is a variable named Y
# 3. Extract data from every column except Outcome column in a variable named X.
# 4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
# 5. Create and train Random Forest Model on training set
# 6. Make predictions based on the testing set using the trained model
# 7. Check the performance by calculating the confusion matrix and accuracy score of the model 

In [ ]:
#1. Load the dataset using pandas
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#2. Extract data from Outcome column is a variable named Y
Y = df.iloc[:,-1]

In [ ]:
#3. Extract data from every column except Outcome column in a variable named X.
X = df.iloc[:,:8]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
#from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1)

In [ ]:
#5. Create and train Random Forest Model on training set
from sklearn.ensemble import RandomForestClassifier
rdm = RandomForestClassifier()
rdm.fit(X_train,Y_train)

RandomForestClassifier()

In [ ]:
#6. Make predictions based on the testing set using the trained model
Y_pred = rdm.predict(X_test)

In [ ]:
#7. Check the performance by calculating the confusion matrix and accuracy score of the model 
#from sklearn.metrics import confusion_matrix,accuracy_score
results = confusion_matrix(Y_pred,Y_test)

In [ ]:
results

array([[129,  32],
       [ 17,  53]], dtype=int64)

In [ ]:
print((129+53)/(129+32+17+53))

0.7878787878787878


Naive Bayes

In [ ]:
#1. Load the dataset using pandas
#2. Extract data fromOutcome column is a variable named Y
#3. Extract data from every column except Outcome column in a variable named X
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
#5. Create and train Naïve Bayes Model on training set
#6. Make predictions based on the testing set using the trained model
#7. Check the performance by calculating the confusion matrix and accuracy score of the model

In [ ]:
#1. Load the dataset using pandas
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#2. Extract data fromOutcome column is a variable named Y
Y = df.iloc[:,-1]

In [ ]:
#3. Extract data from every column except Outcome column in a variable named X
X = df.iloc[:,:8]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 1)

In [ ]:
#5. Create and train Naïve Bayes Model on training set
from sklearn.naive_bayes import GaussianNB
nbc = GaussianNB()
nbc.fit(X_train,Y_train)

GaussianNB()

In [ ]:
#6. Make predictions based on the testing set using the trained model
Y_pred = nbc.predict(X_test)

In [ ]:
#7. Check the performance by calculating the confusion matrix and accuracy score of the model
from sklearn.metrics import confusion_matrix,accuracy_score
results = confusion_matrix(Y_pred,Y_test)
results

array([[128,  32],
       [ 18,  53]])

In [ ]:
((128+35)/(128+32+18+53))

0.7056277056277056