In [5]:
#Numpy Assignment
import numpy as np

#1. Create a 3x3 matrix array with values ranging from 2 to 10.

m = np.arange(2, 11, 1)
m = m.reshape(3,3)
print(m)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
#2. Create a numpy array having user input values and convert the integer type to the float type of the elements of the array. For instance:
#Original array
#[1, 2, 3, 4]
#Array converted to a float type:
#[ 1. 2. 3. 4.]
import numpy as np
my_array = []
a = int(input("Size of array:"))
for i in range(a):
    my_array.append(float(input("Element:")))
my_array = np.array(my_array)
print(np.floor(my_array))

Size of array:3
Element:1
Element:2
Element:3
[1. 2. 3.]


In [11]:
#3. Write a Numpy program to append values to the end of an array. For instance:
#Original array:
#[10, 20, 30]
#After append values to the end of the array:
#[10 20 30 40 50 60 70 80 90]

original = [10,20,30]
after = [40,50,60,70,80,90]
appended = np.append(original,after)
print(appended)

[10 20 30 40 50 60 70 80 90]


In [13]:
#4. Create two numpy arrays and add the elements of both the arrays and store the result in 
#sumArray.

arr1 = np.arange(5)
arr2 = np.arange(8, 12)
sumArray = np.concatenate((arr1, arr2))
print(sumArray)

[ 0  1  2  3  4  8  9 10 11]


In [18]:
#5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
#the following tasks:

m = np.arange(10, 91, 10)
m = m.reshape(3,3)
print(m)

#a. Extract the 1st row from the array.

print(m[0])

#b. Extract the last element from the array.

print(m[-1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30]
[70 80 90]
