In [4]:
#Numpy Assignment 2

#Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
#Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
#[
# [5, 5, 5],
# [5, 5, 5],
# [5, 5, 5]
#]
import numpy as np

def create_array(row, col, element):
    array = np.full((row, col), element)
    print(array)
    
row = int(input("Enter a row number: "))
col = int(input("Enter a col number: "))
element = int(input("Enter a element number: "))

create_array(row, col, element)

Enter a row number: 3
Enter a col number: 6
Enter a element number: 565
[[565 565 565 565 565 565]
 [565 565 565 565 565 565]
 [565 565 565 565 565 565]]


In [5]:
#2. Create a method that takes n Numpy arrays of same dimensions sums them and return the 
#answer.

import numpy as np

def numpy_array(arr1, arr2):
    my_array_sum = np.add(arr1, arr2)
    return my_array_sum
    
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

numpy_array(arr1, arr2)

array([ 6,  8, 10])

In [13]:
#3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
#numbers N and M. The method should return the top-left N X M sub matrix e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
#top_left_sub_matrix (matrix, 2, 2) -> should return:
# [
# [1, 2]
# [4, 5]
# ]

import numpy as np

def top_left_sub_matrix(mat,n,m):
    mat_slice = mat[:n,:m]
    print(mat_slice)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = int(input("enter a n: "))
m = int(input("enter a m: "))
top_left_sub_matrix(mat,n,m)

enter a n: 2
enter a m: 2
[[1 2]
 [4 5]]


In [17]:
#4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
#numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
#sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
# [
# [5, 6]
# [8, 9]
# ]

import numpy as np

def sub_matrix(mat,n,m):
    mat_slice = mat[n:,m:]
    print(mat_slice)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = int(input("enter a n: "))
m = int(input("enter a m: "))
sub_matrix(mat,n,m)

enter a n: 1
enter a m: 1
[[5 6]
 [8 9]]


In [19]:
#5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
#should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
#standard deviation as values:
# [1, 1, 1]
#solution(arr) -> should return :
# {'mean': 1.0, 'std_dev': 0.0}
import numpy as np

def solution(mat):
    dict_ex = {}
    mean = np.mean(mat)
    std_dev = np.std(mat)
    dict_ex['mean'] = mean
    dict_ex['std_dev'] = std_dev
    return dict_ex

mat = np.array([[1,1,1]])
solution(mat)

{'mean': 1.0, 'std_dev': 0.0}